# Generated by Django 4.2.1 on 2024-06-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
