# Generated by Django 4.2.1 on 2024-06-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='tags', to='Crypto.category'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='crypto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crypto.crypto'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
