# Generated by Django 4.2.1 on 2024-06-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0002_crypto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
