# Generated by Django 4.2.1 on 2024-06-08 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0002_crypto_category_customuser_crypto_alter_crypto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='crypto',
        ),
        migrations.AddField(
            model_name='crypto',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crypto.category'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='crypto',
            field=models.ManyToManyField(blank=True, related_name='tags', to='Crypto.crypto'),
        ),
    ]
