# Generated by Django 4.2.1 on 2024-06-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0003_remove_crypto_category_remove_customuser_crypto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='crypto',
        ),
        migrations.AddField(
            model_name='customuser',
            name='crypto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crypto.crypto'),
        ),
    ]
