# Generated by Django 4.2.1 on 2024-06-08 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0004_remove_customuser_crypto_customuser_crypto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='crypto',
        ),
        migrations.AddField(
            model_name='crypto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
