# Generated by Django 4.2.1 on 2024-06-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0006_alter_category_slug_alter_crypto_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Доступ к сайду администратора'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Администратора'),
        ),
    ]
