# Generated by Django 4.2.1 on 2024-06-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0009_customgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
