# Generated by Django 4.2.1 on 2024-06-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0011_alter_customuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='Crypto.customgroup', verbose_name='Группы'),
        ),
    ]
